name: Sync Secrets to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set YouTube API Key in Vercel
        run: vercel env add YOUTUBE_API_KEY ${{ secrets.YOUTUBE_API_KEY }} --token=${{ secrets.VERCEL_TOKEN }}
